In [1]:
from Unet_backboned import Unet

In [2]:
Unet()

2022-09-03 18:45:12.913700: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-03 18:45:13.424602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14593 MB memory:  -> device: 0, name: Quadro RTX 5000, pci bus id: 0000:65:00.0, compute capability: 7.5


In [3]:
image = np.random.normal(size=(1,160,160,1))

In [4]:
Unet = Unet()

In [7]:
len(Unet.layers)

279

In [5]:
Unet.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 160, 160, 1  0           []                               
                                )]                                                                
                                                                                                  
 rescaling_1 (Rescaling)        (None, 160, 160, 1)  0           ['input_2[0][0]']                
                                                                                                  
 normalization_1 (Normalization  (None, 160, 160, 1)  3          ['rescaling_1[0][0]']            
 )                                                                                                
                                                                                            

In [43]:
import seg as sm

In [44]:
seg_builder = sm.Seg_model_builder()
model = seg_builder.get_model()

In [45]:
model

In [46]:
model.summary()

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_7 (InputLayer)           [(None, 160, 160, 1  0           []                               
                                )]                                                                
                                                                                                  
 stem_conv (Conv2D)             (None, 80, 80, 32)   288         ['input_7[0][0]']                
                                                                                                  
 stem_bn (BatchNormalization)   (None, 80, 80, 32)   128         ['stem_conv[0][0]']              
                                                                                                  
 stem_activation (Activation)   (None, 80, 80, 32)   0           ['stem_bn[0][0]']          

In [8]:
import numpy as np
import math

In [2]:
np.linspace(3,90,5)

array([ 3.  , 24.75, 46.5 , 68.25, 90.  ])

In [3]:
N_data_ps = 90*24

In [4]:
train_ratio = 0.9

In [5]:
duration_serie = 2*24

In [6]:
beg = 3*24

In [10]:
            N_series = math.ceil((1-train_ratio)*(N_data_ps-beg) / (duration_serie))
N_series

5

In [11]:
            series_begs = np.linspace(beg, N_data_ps, N_series)


In [12]:
series_begs

array([  72.,  594., 1116., 1638., 2160.])

In [17]:
np.concatenate([np.arange(i,i+2*24) for i in series_begs])

array([  72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,
         81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,
         90.,   91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,
         99.,  100.,  101.,  102.,  103.,  104.,  105.,  106.,  107.,
        108.,  109.,  110.,  111.,  112.,  113.,  114.,  115.,  116.,
        117.,  118.,  119.,  594.,  595.,  596.,  597.,  598.,  599.,
        600.,  601.,  602.,  603.,  604.,  605.,  606.,  607.,  608.,
        609.,  610.,  611.,  612.,  613.,  614.,  615.,  616.,  617.,
        618.,  619.,  620.,  621.,  622.,  623.,  624.,  625.,  626.,
        627.,  628.,  629.,  630.,  631.,  632.,  633.,  634.,  635.,
        636.,  637.,  638.,  639.,  640.,  641., 1116., 1117., 1118.,
       1119., 1120., 1121., 1122., 1123., 1124., 1125., 1126., 1127.,
       1128., 1129., 1130., 1131., 1132., 1133., 1134., 1135., 1136.,
       1137., 1138., 1139., 1140., 1141., 1142., 1143., 1144., 1145.,
       1146., 1147.,